-- v1.1 features: file attachments, pricing approvals, idempotent notes
-- Generated by hand because Docker wasn't available to run prisma migrate diff
-- with a shadow DB. Mirrors the schema changes 1:1.

-- Note idempotency
ALTER TABLE "notes" ADD COLUMN "client_id" TEXT;
CREATE UNIQUE INDEX "notes_lead_id_client_id_key" ON "notes"("lead_id", "client_id");

-- File attachments
CREATE TABLE "attachments" (
    "id" UUID NOT NULL,
    "lead_id" UUID NOT NULL,
    "uploaded_by_user_id" UUID NOT NULL,
    "filename" TEXT NOT NULL,
    "content_type" TEXT NOT NULL,
    "byte_size" INTEGER NOT NULL,
    "storage_path" TEXT NOT NULL,
    "public_url" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "attachments_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "attachments_lead_id_idx" ON "attachments"("lead_id");
ALTER TABLE "attachments"
    ADD CONSTRAINT "attachments_lead_id_fkey"
    FOREIGN KEY ("lead_id") REFERENCES "leads"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "attachments"
    ADD CONSTRAINT "attachments_uploaded_by_user_id_fkey"
    FOREIGN KEY ("uploaded_by_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- Pricing approval workflow
CREATE TYPE "PricingApprovalStatus" AS ENUM ('PENDING', 'APPROVED', 'REJECTED');

CREATE TABLE "pricing_approvals" (
    "id" UUID NOT NULL,
    "lead_id" UUID NOT NULL,
    "requester_user_id" UUID NOT NULL,
    "approver_user_id" UUID,
    "sticker_price" DECIMAL(12,2) NOT NULL,
    "proposed_price" DECIMAL(12,2) NOT NULL,
    "discount_pct" DECIMAL(5,2) NOT NULL,
    "reason" TEXT NOT NULL,
    "status" "PricingApprovalStatus" NOT NULL DEFAULT 'PENDING',
    "decided_at" TIMESTAMP(3),
    "decision_note" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "pricing_approvals_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "pricing_approvals_lead_id_idx" ON "pricing_approvals"("lead_id");
CREATE INDEX "pricing_approvals_status_idx" ON "pricing_approvals"("status");
ALTER TABLE "pricing_approvals"
    ADD CONSTRAINT "pricing_approvals_lead_id_fkey"
    FOREIGN KEY ("lead_id") REFERENCES "leads"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "pricing_approvals"
    ADD CONSTRAINT "pricing_approvals_requester_user_id_fkey"
    FOREIGN KEY ("requester_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "pricing_approvals"
    ADD CONSTRAINT "pricing_approvals_approver_user_id_fkey"
    FOREIGN KEY ("approver_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
